### ISSUE TITLE
[Bug] `refElement` can't be typed as an SVGElement as it's type extends HTMLElement

### ISSUE THREAD

**Issue by ReneDrie** [mubanjs/muban#11]
Using the following in refs definitions throws a TS error
```maskSvg: refElement<SVGElement>('mask-svg'),```

The type for the `refElement` = `T extends HTMLElement`. Maybe this should be `Element` or `HTMLOrSVGElement`?

**Comment by ThaNarie** [comment]
Probably best to change it to a union yes (going to `Element` would be missing a lot of properties we expect to use).
