### ISSUE TITLE
[props] allow defining an array of sources, where it picks the first defined

### ISSUE THREAD

**Issue by ThaNarie** [mubanjs/muban#25]
Component Prop definitions, that extract information from the rendered HTML, can provide a "source".

A source specifies where to extract something from specifically (https://mubanjs.github.io/muban/api/props.html#source), and is a combination of a target and a type (an attribute, the existence of a css class, the text contents, etc) with some additional configuration.

Sometimes certain data is rendered differently in the HTML (e.g. an input element, that requires the `value` source type, versus a textarea, which requires the `text/html` source type).

As a developer you might know that always one of them is rendered, but not which one. The data always exists, and it doesn't matter which one it comes from for the rest of the component.

In that case, it would be useful to allow specifying an array of source configurations, where they are tried in order. If the target doesn't exist, or value is undefined, it tries the next one

Tasks:
- [ ] make unit tests for this new feature
- [ ] implement this new feature
- [ ] update the docs to explain this feature

**Comment by jspolancor** [comment]
I'm making good progress on this issue, but I'm not sure what to do with the **hasProp** and **getProp** functions in the createAttriburePropertySource file. In the hasProp func, If an array of sources is provided should we check the target for each one? and in the getProp what should we return? an array of values for each source provided 🤔? what do you think?

**Comment by ThaNarie** [comment]
`hasProp`, similar to `.some` – if some of the sources match, return `true`
`getProp` similar to `.find` – return the first source match.
