### ISSUE TITLE
Make it possible to toggle styling attribute

### ISSUE THREAD

**Issue by tworrisb** [mubanjs/muban#64]
When setting a styling attribute you always have to set something. Would be a nice feature to also accept undefined instead of having to set an empty string.

```ts
// Current situation:
top: computed(() => someBoolean.value ? `${props.variablePx}px` : '')

// Proposed possibility:
top: computed(() => someBoolean.value && `${props.variablePx}px`)
```

**Comment by ThaNarie** [comment]
@jspolancor I think we can change the type of the style binding to support `null` and `undefined` as values, and check if they are handled correctly in the binding code.

**Comment by jspolancor** [comment]
I like the idea of having undefined style properties, however, the proposed possibility is never going to work as typescript always types the return as a boolean after a short circuit evaluation inside the return calculation of a function.

![image](https://user-images.githubusercontent.com/5639960/156079657-1b91de88-cc9c-496f-9e02-eeff0ac61737.png)

Not even possible typing the function's return

![image](https://user-images.githubusercontent.com/5639960/156079690-b0e26f95-6988-4050-95f7-640194977fb7.png)

So if we modify the types we are not going to be able to use the proposed possibility, as the functions inside the _computed()_ will always be typed as booleans

**Comment by ThaNarie** [comment]
That's because TS knows the type of `someBoolean` in your example (in this case, you assigned a `false` value.
If you look at something more generic in the TS Playground, you see it work just fine:

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOcAUMwAcRQFyIBGqANgKYCGYAlIgN4BQiziATmVCK0pjlIgDIBiAOQo4IgNwMAvkA

```
function foo(input: boolean) {
    return input && 'foo';
}
```

return type is `false | 'foo'`

**Comment by ThaNarie** [comment]
`computed` doesn't expect any parameters, so you took my example out of context. It was only a reply to your original code, that used an anonymous function as a test :)

The change for the reported "feature" should be fairly simple – and has nothing to do do with the code you _pass_ to the binding. It's about letting the `style` bindings accept non-string values.

Currently it's defined as:
```ts
export function styleBinding(target: HTMLElement, valueAccessor: BindingMap<string>) {
```

So `BindingMap<string>` should become something like `BindingMap<string | null | undefined | false>` :)
