### ISSUE TITLE
`watch` and `watchEffect` behave different in Muban vs Vue

### ISSUE THREAD

**Issue by ThaNarie** [mubanjs/muban#65]
* `watchEffect` is not triggered by an reactive object by itself
* `watch` is running in a different `flush` mode, delaying the invocation of the callback, and "batching" so it only picks up the latest change in a sync operation.

Code example:
```ts
const r = reactive({});
  
watchEffect(() => console.log('watchEffect', r));
watch(r, value => console.log('watch', value));
  
r.foo = 1;
r.foo = 2;
```

In Vue, this triggers
* initial `watchEffect`
* the `watchEffect` and `watch` for both changes, with their respective values

https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cblx0aW1wb3J0IHsgcmVhY3RpdmUsIHdhdGNoLCB3YXRjaEVmZmVjdCB9IGZyb20gJ3Z1ZSdcblxuXHRjb25zdCByID0gcmVhY3RpdmUoe30pO1xuICBcbiAgd2F0Y2hFZmZlY3QoKCkgPT4gY29uc29sZS5sb2coJ3dhdGNoRWZmZWN0JywgcikpO1xuICB3YXRjaChyLCB2YWx1ZSA9PiBjb25zb2xlLmxvZygnd2F0Y2gnLCB2YWx1ZSkpO1xuICBcbiAgci5mb28gPSAxO1xuICByLmZvbyA9IDI7XG4gIFxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgb3BlbiBjb25zb2xlXG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vc2ZjLnZ1ZWpzLm9yZy92dWUucnVudGltZS5lc20tYnJvd3Nlci5qc1wiXG4gIH1cbn0ifQ==

In Muban, this triggers:
* initial `watchEffect`
* Only the latest `watch` with the latest value.

When adding `{ flush: 'sync' }` to the `watch`, it's triggered for both changes.

https://codesandbox.io/s/muban-watch-effect-1uq86z?file=/src/App.ts

**Comment by ThaNarie** [comment]
Did some research, the logic is in:

https://github.com/vuejs/core/blob/main/packages/runtime-core/src/apiWatch.ts#L346-L357

Specifically `if (!instance || instance.isMounted) {`

So:
* When used outside of a component, it's `pre` by default
* If it's used directly in the `setup`, it's `sync` by default – this is where the differences in the test came from
* If it's used **after** being `mounted`, it's `pre` by default

Since Muban doesn't have a **vue** `instance`, it always runs in the "outside of a component" mode.

This applies to both `watch` and `watchEffect`.

---

Based on this, we have a few options:

1. Don't do anything, but document that the `default` is **always** `pre`, and you can change it to `{ flush: 'sync' }` if you need direct effects.
2. Change the default to `sync` if we feel this is desired. Downside is that the default performance is "worse", since it won't do any batching.
3. From within Muban, set the Vue `currentInstance` as well, so Muban behaves exactly the same as Vue. Done in https://github.com/vuejs/core/blob/main/packages/runtime-core/src/component.ts#L550

Note regarding 3️⃣, the `watch` and `watchEffect` are the only APIs that we use from `@vue/runtime-core`, and would have anything to do with the component instance. The scope here is very limited, to mostly calling things with error handling. And if the `instance.vnode` is `undefined` (which it always is), it behave the same as it currently does. So not a huge impact.

@psimk @jspolancor @ThijsTyZ @larsvanbraam Any preferences or thoughts?

**Comment by ThijsTyZ** [comment]
I would have a preference for `3` as this feels more intuitive to me.

**Comment by ThaNarie** [comment]
Looks like the behaviour of Vue itself changed in recent 2.34:
<img width="399" alt="image" src="https://user-images.githubusercontent.com/1449580/192844447-05f5feae-5a90-4061-a0b2-5e9cb81684ad.png">

It no longer logs all changes that happen during setup.
And the code reflects this change as well, as the previous linked highlighted section doesn't include the `if (!instance || instance.isMounted) {` change anymore.

Will need to do a few more tests to see if there are still some differences, or if this change was intentional, but otherwise it might have been solved for us :)

**Comment by ThaNarie** [comment]
Closing this issue, since:

> watchEffect is not triggered by an reactive object by itself

Unsure if this is true, the code seems to be triggered by it. Unclear what issue this currently has (e.g. does it mean that some bindings are not updated when using reactive objects?)

> watch is running in a different flush mode, delaying the invocation of the callback, and "batching" so it only picks up the latest change in a sync operation.

This seems to be fixed in Vue itself, removing the `sync` codepath when run in setup function directly.
