### ISSUE TITLE
Add input-specific `propType.source` type

### ISSUE THREAD

**Issue by ThaNarie** [mubanjs/muban#67]
Most of the current sources read HTML values / attributes, but for `input` elements it is sometimes needed to get the actual "current" value from the JS API, since it could have been changed before the component was initialized.

Example; a text input could get auto-filled, but the `getAttribute('value')` returns the server-rendered value, which is outdated.

Proposal:
```ts
// when `name` is given, the `target` should be the form
// it will then use the `FormData` to access the values
// this supports cases where multiple elements share the same `name` attribute (like checkboxes)
propType.source({ type: 'form', target: 'formRef', name: 'choices');

// or a simple way to extract a value from a single form element
propType.source({ type: 'form', target: 'inputRef' });
```

#### target is `input` with `type="text|number|date|password|..."`, `textarea` or `select`

Return its `value`.

```html
<input type="text" />
<input type="number" />
<input type="date" />
<textarea></textarea>
<select> ... </select>
```
```ts
propType.string.source({ type: 'form', target: 'inputRef' })
propType.number.source({ type: 'form', target: 'numInputRef' })
propType.date.source({ type: 'form', target: 'dateInputRef' })
propType.string.source({ type: 'form', target: 'textareaRef' })
propType.string.source({ type: 'form', target: 'selectRef' })
```

> **Note:** the `type` should support any type that we don't support specifically in one of the other cases below.

#### target is `input` with `type="checkbox"`

Detect the `propType` of the `prop`

* when `boolean`, return the `checked` property (either `true` or `false`)
* `else` (mostly `string`), return the `value` when the checkbox is `checked`

```html
<input data-ref="input" type="checkbox" value="foo" />
<input data-ref="inputChecked" type="checkbox" value="foo" checked />
```
```ts
propType.boolean.source({ type: 'form', target: 'inputRef' }) // false
propType.string.source({ type: 'form', target: 'inputRef' }) // undefined
propType.boolean.source({ type: 'form', target: 'inputCheckedRef' }) // true
propType.string.source({ type: 'form', target: 'inputCheckedRef' }) // foo
```

#### target is `select` with `multiple`

Use the `selectedOptions` to return an `Array` of the `values`.

We should expect a `propType.array` here, if it's not we should log an `Error`, but still convert the values to the requested data type (e.g. comma-separated string).

```html
<select multiple> ... </select>
```
```ts
propType.array.source({ type: 'form', target: 'selectRef' }) // ['foo', 'bar']
propType.string.source({ type: 'form', target: 'selectRef' }) // 'foo,bar' + error log
```

#### target is `input` with `type="file"`

We make use of the `files` property to return a `FileList`.

* When specified `propType.array`, we return that list as an `Array`.
* When specified `propType.object`, we return the first `File` item – and log an `Error` when it could accept `multiple`.

```html
<input data-ref="input" type="file" />
<input data-ref="inputMultiple" type="file" multiple />
```
```ts
propType.array.source({ type: 'form', target: 'inputRef' }) // [File]
propType.object.source({ type: 'form', target: 'inputRef' }) // File
propType.array.source({ type: 'form', target: 'inputMultipleRef' }) // [File, File, File]
propType.object.source({ type: 'form', target: 'inputMultipleRef' }) // [File] + error log
// anything else = undefined + error log
```

#### target is `form`

Use the `FormData` api to retrieve the value.

* When `name` option is present, return the matching `FormData` entry
* When the `name` option is omitted, return the complete `FormData` object – and log an `Error` when `propType.object` is not specified.

Using this method, we cannot detect if a field can or will appear multiple time (e.g. a `multiple` `select`, or **checkboxes**). Unless specified otherwise, we will use the `getAll`, and depending on the `propType` we return an `Array` or stringified version.

```html
<form>
  <input name="firstName" type="text" />
  <textarea name="description"></textarea>
  <select name="preference"> ... </select>

  <input name="optionA" type="checkbox" />
  <input name="optionB" type="checkbox" checked />
  <input name="choices" type="checkbox" value="apple" />
  <input name="choices" type="checkbox" value="banana" checked />

  <select name="candidates" multiple> ... </select>

  <input name="photo" type="file" />
</form>
```
```ts
// complete form
propType.object.source({ type: 'form', target: 'formRef'); // FormData

// individual fields
propType.string.source({ type: 'form', target: 'formRef', name: 'firstName');
propType.string.source({ type: 'form', target: 'formRef', name: 'description');
propType.string.source({ type: 'form', target: 'formRef', name: 'preference');

propType.boolean.source({ type: 'form', target: 'formRef', name: 'optionA'); // false
propType.boolean.source({ type: 'form', target: 'formRef', name: 'optionB'); // true
propType.array.source({ type: 'form', target: 'formRef', name: 'choices'); // ['banana']

propType.array.source({ type: 'form', target: 'formRef', name: 'candidates'); // ['John', 'Jane']

propType.object.source({ type: 'form', target: 'formRef', name: 'photo'); // File

```

### Unclear

 * What to do with the `indeterminate` setting of a `checkbox`? return `undefined` ?

**Comment by ThijsTyZ** [comment]
Good proposal. I think we could do things based on the propType:

- For a `checkbox` is the propType is `boolean` return the `checked` value. If it's a `string` return the `checked value` if the `checkbox` is checked, otherwise return `undefined`.
- Agree about your suggestion about Arrays. Maybe we should show an error when there are multiple values, but the propType is not an Array?
- What about files? There is currently no propType for that. Or we ignore this, because we probably never need it.

**Comment by ThijsTyZ** [comment]
What should happen if you specify a `name`, but the `target` is not a `<form>`?

**Comment by ThaNarie** [comment]
> What should happen if you specify a name, but the target is not a <form>?
log an error, and return `undefined`?

> For a checkbox is the propType is boolean return the checked value. If it's a string return the checked value if the checkbox is checked, otherwise return undefined.
Sounds like a plan :)

> Agree about your suggestion about Arrays. Maybe we should show an error when there are multiple values, but the propType is not an Array?
Could work as well, but what would we return in that case?

> What about files? There is currently no propType for that. Or we ignore this, because we probably never need it.
Good one, we could support it with the value that would otherwise come out of the `FormData`.

**Comment by ThijsTyZ** [comment]
> Agree about your suggestion about Arrays. Maybe we should show an error when there are multiple values, but the propType is not an Array?
> 
> Could work as well, but what would we return in that case?

Let's do your proposal of a comma separated string

**Comment by ThaNarie** [comment]
I updated the issue itself based on the above conversation, and added some clear examples.

There is one "unclear" thing remaining. But I feel we could already start the implementation.

**Comment by ThaNarie** [comment]
> although the browsers don't support this

What do you mean with "don't support" ?
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#indeterminate_state_checkboxes

I think `undefined` might be a good option, since:

> Note: If you submit a form with an indeterminate checkbox, the same thing happens as if the checkbox were unchecked — no data is submitted to represent the checkbox.
