### ISSUE TITLE
[Bug] AppComponents are initialized twice when adding as a refComponent

### ISSUE THREAD

**Issue by larsvanbraam** [mubanjs/muban#8]
**Issue**
I noticed that when I added a component to the `appComponents` to allow for global initialization it got initialized again when used as a `refComponent`

Note: this applies to running the dev server through `yarn dev`

**How to reproduce**
```ts
// index.ts

import { createApp } from '@muban/muban';
import { App } from './App';
import { SomeComponent } from './components/some-component/SomeComponent';

const app = createApp(App);
// eslint-disable-next-line no-restricted-properties
const element = document.querySelector<HTMLElement>('#app');

if (element) {
  app.component(SomeComponent);
  app.mount(element);
}
```

```ts
// SomeOtherComponent.ts

import { defineComponent, refComponent } from '@muban/muban';
import { SomeComponent } from '../some-component/SomeComponent';

export const SomeOtherComponent = defineComponent({
  name: 'some-other-component',
  refs: {
    someComponent: refComponent(SomeComponent),
  }
})
```

Then when we add the _some-component_ to our _some-other-component_ parent we will notice the double component initialization.

```ts
// SomeComponent.ts

import { defineComponent, refComponent } from '@muban/muban';
import { SomeComponent } from '../some-component/SomeComponent';

export const SomeComponent = defineComponent({
  name: 'some-component',
  setup() {
    // This will be executed twice even though it should only be once!
  }
})
```

**Console screenshot**

![image](https://user-images.githubusercontent.com/5783689/118767507-21f49800-b87e-11eb-9a13-22dc5c1fe7cf.png)

**Comment by skulptur** [comment]
Hi @larsvanbraam

We tried to replicate this. In the template we had:
```html
<div data-component="some-other-component">
   <div data-component="some-component"></div>
</div>
```

But if we use your first code snippet with `app.component(SomeComponent);` then we only get SomeComponent initialized once as expected as that is the one without refs.

If we change that to `app.component(SomeOtherComponent);` then we see both are initialized, but only 1 time each as expected.

We're noobs on this so maybe we are failing to replicate correctly, would appreciate if you have any more pointers!

Thanks

**Comment by larsvanbraam** [comment]
Hey @skulptur 

After a little further investigation I found out it only happens when the parent component is a `lazy` component. 

In this scenario, the `SomeComponent` is initialized as soon as it's in the DOM because we added it to the 
`app.component(SomeComponent);`

But then once the lazy component is loaded it will cause the `SomeComponent` to be initialized again 🤔 

![image](https://user-images.githubusercontent.com/5783689/124082148-a9702200-da4c-11eb-883c-119796c2c511.png)

I've created a branch where you can see this in action → `bug/components-initialized-twice`

This branch is purely for demonstration purposes so please make sure to not merge it! 🤓
