### ISSUE TITLE
Make re-binding a prop smarter

### ISSUE THREAD

**Issue by larsvanbraam** [mubanjs/muban#84]
Imagine the following scenario:

```ts
// A simple component that has a value applied as an attribute
const someComponentTemplate = (props) => 
  html`<button data-component="some-component" value=${props.value}>${props.label}</button>`;

// The component also has a binding where we can modify the value.
const SomeComponent = defineComponent({
   name: 'some-component',
   props: {
    value: propType.number.source({ type: 'attr' }),  // ← Note how we state that this prop is a number
  },
  setup({ refs, props }) {
    return [
       bind(refs.self, {
         attr: {
           value: computed(() => props.value), // ← But when applying this binding we get an error as soon as we modify the value!
         }
      }),
    ]
  }
})
```
I would expect this to work but it gives me the following error in the console:

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/5783689/185099759-b033b886-7fb6-4b2b-972c-1755640da778.png">

The workaround here would be to first parse the value back to a string like so:

```ts
bind(refs.self, {
  attr: {
    value: computed(() => props.value.toString())
  }
})
```

But I would assume that we could come up with a smarter approach here where the type is automatically inferred or something! 🤓

**Comment by ThaNarie** [comment]
Automatic inference would be super tricky, but maybe we could just loosen the type of attrs and do a `toString` by default.

**Comment by jspolancor** [comment]
@ThaNarie I've been testing this for a few hours and noticed a few things:
The error message from the screenshot is actually from the `valueBinding()` and not from the `attrBinding()`, I was a little confused because that log message from the screenshot is only executed inside the `checkInitialBindingState()` function, and we're not using that function inside the `attrBinding()`, somehow when Lars discovered this issue the wrong binding was being executed, I tried with the same code Lars provided and I never got the error message in the console, am I missing something? or was this issue solved in another commit without we noticing? 🤔

**Comment by ThaNarie** [comment]
Hmm you are correct, the error is from the `value` binding (on input/textarea/select elements), not from the `attr` binding.

I think @larsvanbraam made a typo when providing this example (to not share the code of the actual project), and it should have been the value binding on an input element. @larsvanbraam can you confirm?

I presume that scenario would give the reported error, could you try to reproduce _that_ instead @jspolancor ?

**Comment by jspolancor** [comment]
> Hmm you are correct, the error is from the `value` binding (on input/textarea/select elements), not from the `attr` binding.
> 
> I think @larsvanbraam made a typo when providing this example (to not share the code of the actual project), and it should have been the value binding on an input element. @larsvanbraam can you confirm?
> 
> I presume that scenario would give the reported error, could you try to reproduce _that_ instead @jspolancor ?

Yes, that will trigger the log, but I don't think thats an error in the context of the valueBinding(), when setting an input value the type should be explicit

**Comment by ThaNarie** [comment]
> when setting an input value the type should be explicit

Well, that's the whole discussion for this issue :)

It seems like the code is allowed, but it throws a runtime error. If we don't want that, we have two directions to go in:

1. make TS stricter so it only allows strings
2. make our binding looser (smarter), and convert basic primitives (number, bool) to strings automatically.

I can't think of a huge downside for option two, so I'm leaning in that direction.
