### ISSUE TITLE
[Bug] Child components with the same ref name are not found

### ISSUE THREAD

**Issue by larsvanbraam** [mubanjs/muban#9]
I noticed that child components that use the same name for a ref cause the main ref to no longer be found.

**Example scenario**

```ts
export const ParentComponent = defineComponent({
  name: 'parent-component',
  refs: {
    someChild: refComponent(ChildComponent, { ref: 'some-child'  }),
  }
});

export const ChildComponent = defineComponent({
  name: 'child-component',
  refs: {
    // This component also has a ref that is named `some-child`
    someOtherChild: refComponent(SomeOtherChild, { ref: 'some-child' }),
  }
});
```

**Result**

The following error is displayed for the `ParentComponent` in the console:

> Component not found [data-ref="some-child"]

**Comment by jyggiz** [comment]
Hello! With this example, I was unable to reproduce this bug. Is it still relevant? If you have time, can you please share the details of this case @larsvanbraam? Thank you!

**Comment by ThaNarie** [comment]
Added bugfix/9-child-components-with-the-same-ref-name-are-not-found with a story, but it's not showing the issue.

I need more info to reproduce and fix this.

**Comment by larsvanbraam** [comment]
@ThaNarie @jyggiz I'm also no longer able to reproduce the original issue, weird! 🤔  

I was able to locate another weird issue where the `refElement` returned the same element as the `refs.self.element` when they both use the same `data-ref` value. I've updated the branch to demonstrate the issue!

**Comment by ThaNarie** [comment]
> I was able to locate another weird issue where the refElement returned the same element as the refs.self.element when they both use the same data-ref value.

This is by design (and requested as a convenience feature), to keep a data-ref working when moving it to the data-component element. It's slightly confusing when both parents and components can target the same element when they use the same ref, and it gets priority.

Changing it to only use it as fallback could result in weird behaviour with optional refs (sometimes falling back to the root element, and sometimes selecting the correct child elements).

**Comment by larsvanbraam** [comment]
Ok, then I'll close and mark this one as invalid!
